[package]
name = "merkle_tree"
version = "0.1.0"
authors = ["Jagrut Kosti <jagrut.kosti@porsche.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.2"
hex = "0.4.2"
bytevec = "0.2.0"